### ISSUE TITLE
IV interpreted as str

### ISSUE THREAD

**Issue by J3y0** [t0thkr1s/gpp-decrypt#4]
Hi ! 

First of all, I wanted to thank you for the tool. 

**My problem**

When using it, the code didn't work and I didn't understand why. I had this error:
```
TypeError: Object type <class 'str'> cannot be passed to C code
```

After some testing on my side of the code, I discover the line: `aes = AES.new(key, AES.MODE_CBC, iv)` was the problem. 
Indeed, the notation: `iv = '\x00' * 16` can be confusing for python and was interpreted as string. (I am using Python 3.10.5)

The new code would be `iv = b'\x00' * 16` and it solves the problem.

Regards

**Comment by t0thkr1s** [comment]
Hi! 

There was pull request made by @OXDBXKXO and I just merged it, so it's resolved. Thank you for noticing and opening an issue about it!
